var completers = new Array(
"  63 Oliver Salmon--------------------- Sep-24",
"  62 Alan Duval (NPR) 2nd round ------- Apr-23",
"  61 Kathy Duval (NPR) 2nd round ------ Apr-23",
"  60 Matthew Bourne (NPR)-------------- May-22",
"  59 Sarah Bourne (NPR)---------------- May-22",
"  58 Andrew Micklewright (NPR)--------- Sep-21",
"  57 Bernadette Micklwright (NPR)------ Sep-21",
"  56 Tom Hayek------------------------- Jul-19",
"  55 Phillip Day----------------------- Nov-19",
"  54 Richard Day----------------------- Nov-19",
"  53 Christine Shepherd---------------- Jun-17",
"  52 Chris Johnson--------------------- Mar-17",
"  51 Peter Stone----------------------- Dec-16",
"  50 David Garside (NPR)--------------- Oct-15",
"  49 Kenneth Highley (NPR)------------- Aug-15",
"  48 David Highley (NPR)--------------- Aug-15",
"  47 Nigel Mason (NPR)----------------- Aug-15",
"  46 Toby Harling---------------------- Jul-15",
"  45 Ronnie Bowron--------------------- Sep-14",
"  44 David Bibby----------------------- Dec-13",
"  43 Richard Slack--------------------- Aug-13",
"  42 Mike Cunningham (NPR)------------- Jun-13",
"  41 Steve Smith (NPR)----------------- Apr-13",
"  40 Colin Wilkinson (NPR)------------- Aug-12",
"  39 Stephen Mawby (NPR)--------------- Jul-12",
"  38 Michael Finnigan (NPR)------------ Jul-12",
"  37 Jason Houghton (NPR)-------------- Nov-11",
"  36 Martin Roberts-------------------- Oct-11",
"  35 Jeff Ford------------------------- Oct-11",
"  34 Roger Chapman--------------------- Sep-11",
"  33 David Ward------------------------ Jun-11",
"  32 Heather Ward (NPR)---------------- Jun-11",
"  31 Ian Brown------------------------- Mar-11",
"  30 Teresa Brown---------------------- Mar-11",
"  29 Mark Hallam (NPR)----------------- Aug-10",
"  28 Alex Hardisty--------------------- Jul-10",
"  27 David Brown ---------------------- Dec-09",
"  26 Warwick Peirson------------------- Sep-09",
"  25 John Jennison--------------------- May-09",
"  24 Eric Binns------------------------ May-09",
"  23 Adrian Wade (NPR)----------------- Aug-08",
"  22 Susan Wade (NPR)------------------ Aug-08",
"  21 Trevor Mason (NPR)---------------- Aug-07",
"  20 Stuart Henderson (NPR)------------ Jun-07",
"  19 Anne Henderson (NPR)-------------- Jun-07",
"  18 Matthew Webster------------------- Oct-06",
"  17 George Hladowski (NPR)------------ Jul-06",
"  16 Bill Gardner(Tim's dog) (NPR)----- Feb-05",
"  15 Steve Fletcher-------------------- Aug-04",
"  14 Mal Walker (NPR)------------------ Aug-04",
"  13 Annie (NPR) (John & Barbara's dog) May-03",
"  12 John Twidale (NPR)---------------- May-03",
"  11 Barbara Twidale (NPR)------------- May-03",
"  10 Dennis Foster (NPR)--------------- Feb-03",
"   9 Paul Nichols (NPR)---------------- Jan-02",
"   8 Storm (Martin's dog)-------------- Jan-01",
"   7 Chris Scaife---------------------- Nov-00",
"   6 Rob Scaife------------------------ Nov-00",
"   5 Alec Burford---------------------- Sep-00",
"   4 Margaret Burford------------------ Sep-00",
"   3 Paul Lyons------------------------ Jun-99",
"   2 Gill Lyons------------------------ Jun-99",
"   1 Bryan Spark----------------------- Jun-99"
);
