var completers = new Array(
" 347 Julie Gardner--------------------- Jul-24",
" 346 Simon Mason----------------------- Jul-24",
" 345 Mick Peakman---------------------- Jul-24",
" 344 Peter Lancaster------------------- Jul-24",
" 343 Louise Terril (NPR)--------------- May-24",
" 342 Richard Kennaugh (NPR)------------ May-24",
" 341 Steve Jackson--------------------- Apr-24",
" 340 Lotte Gale (NPR)------------------ Oct-23",
" 339 Peter Grayson--------------------- Jun-23",
" 338 Neil Stutchbury------------------- Apr-23",
" 337 Alan Duval (NPR)------------------ Apr-23",
" 336 Kathy Duval (NPR)----------------- Apr-23",
" 335 Bryony Carter--------------------- Jul-22",
" 334 Tim Barnes------------------------ Jun-22",
" 333 Mike Doughty---------------------- Jun-22",
" 332 Jim Linton (NPR)------------------ Sep-21",
" 331 Rick Salter----------------------- Jul-21", 
" 330 Jenny Hatfield-------------------- Jul-21",
" 329 Mike Boothman--------------------- May-21",
" 328 Helen Boothman-------------------- May-21",
" 327 Mike Day-------------------------- Oct-20",
" 326 Peter Ibison---------------------- Aug-20",
" 325 Malcolm Rogers-------------------- Aug-20",
" 324 Anne Rogers----------------------- Aug-20",
" 323 Neil Midgley---------------------- Jul-20",
" 322 John Green------------------------ Oct-19",
" 321 Malcolm Barrett------------------- Sep-19",
" 320 Paul Gregson---------------------- Aug-19",
" 319 Anne Gregson---------------------- Aug-19",
" 318 Ruth Martin----------------------- Jul-19",
" 317 Nigel Mason (NPR)----------------- Jun-19",
" 316 Jim Hatfield---------------------- Mar-19",
" 315 Mike Wells------------------------ Mar-19",
" 314 Tim Sharp------------------------- Mar-19",
" 313 Howard Jones---------------------- Nov-18",
" 312 Ken Whyte------------------------- Sep-18",
" 311 Colin Shearer--------------------- Sep-18",
" 310 Jenny Barnard (NPR)--------------- Sep-18",
" 309 John Barnard (NPR)---------------- Sep-18",
" 308 Alex Hardisty--------------------- Sep-18",
" 307 David Garside--------------------- Aug-18",
" 306 Howard Mann----------------------- Jul-18",
" 305 Gordon Coventry------------------- Sep-17",
" 304 Adrienne Coventry----------------- Sep-17",
" 303 James Forrest--------------------- Sep-17",
" 302 Diane Pickering------------------- Sep-17",
" 301 Christine Gordon------------------ Sep-17",
" 300 John Hart------------------------- Sep-17",
" 299 Katherine Hart-------------------- Sep-17",
" 298 John Jennison--------------------- Sep-17",
" 297 Andy Moon------------------------- Aug-17",
" 296 Sarah Marlor---------------------- Aug-17",
" 295 Mark Lloyd------------------------ Aug-17",
" 294 John Burgess (NPR)---------------- Jul-17",
" 292 Peter Yoxall---------------------- Apr-17",
" 291 Martin Roberts-------------------- Apr-17",
" 290 Peter Smith (NPR)----------------- Jan-17",
" 289 Steve Smith----------------------- Nov-16",
" 288 Paul Kirkwood--------------------- Oct-16",
" 287 Gill Sanderson ------------------- Oct-16",
" 286 Steve Sanderson ------------------ Oct-16",
" 285 Stephen Walker-------------------- Jun-16",
" 284 Alan Tinker----------------------- Jun-16",
" 283 Ivan Grindrod--------------------- Jun-16",
" 282 John Astbury---------------------- Jun-16",
" 281 Ronnie Bowron--------------------- May-16",
" 280 John Burgess (NPR)---------------- May-16",
" 279 David Pettit---------------------- May-16",
" 278 Sharron Rogers-------------------- Oct-15",
" 277 Chris Rogers---------------------- Oct-15",
" 276 Matthew Braithwaite (NPR)--------- Sep-15",
" 275 Ted Richards (NPR)---------------- Sep-15",
" 274 Caroline Roy---------------------- Aug-15",
" 273 Nick Norman----------------------- Aug-15",
" 272 Tony Hill------------------------- Aug-15",
" 271 Guy Froud------------------------- Jun-15",
" 270 Steve Stobie (NPR)---------------- Jun-15",
" 269 Philip Massey--------------------- May-15",
" 268 Gerry Bowes----------------------- May-15",
" 267 John Farrow----------------------- May-15",
" 266 David Stearne--------------------- May-15",
" 265 Vince Joyce (NPR)----------------- Oct-14",
" 264 Meirion Evans--------------------- Sep-14",
" 263 John Burton----------------------- Aug-14",
" 262 Stephen P. Smith------------------ Jul-14",
" 261 Stephen Mawby (NPR)--------------- Jul-14",
" 260 Mike Finnigan (NPR)--------------- Jul-14",
" 259 Peter M. Young-------------------- May-14",
" 258 Jeff Ford------------------------- May-14",
" 257 Kathy Duval (NPR)----------------- Apr-14",
" 256 Alan Duval (NPR)------------------ Apr-14",
" 254 Nigel Thackrah-------------------- Jan-14",
" 253 Mike Saul------------------------- Oct-13",
" 252 Peg Saul-------------------------- Oct-13",
" 251 Terry Fuller---------------------- Sep-13",
" 250 Richard Fuller-------------------- Sep-13",
" 249 John Balmforth-------------------- Sep-13",
" 248 Steve Ward------------------------ Aug-13",
" 247 Christine Stratton---------------- Aug-13",
" 246 Steve Hudson---------------------- Jul-13",
" 245 Malcolm Bee----------------------- Jul-13",
" 244 Kevin Jones----------------------- Jul-13",
" 243 Carol Gruffydd-------------------- Jul-13",
" 242 Kenneth Highley------------------- Jun-13",
" 241 David Highley--------------------- Jun-13",
" 240 Andy Hyams------------------------ Jun-13",
" 239 Andrew Larkins-------------------- Jun-13",
" 238 Martin Clarke--------------------- May-13",
" 237 Jeffrey Hobbs--------------------- May-13",
" 236 Darran Moss----------------------- May-13",
" 235 Nicola Moss (NPR)----------------- May-13",
" 234 Jules Alexandrou------------------ Dec-12",
" 233 Colin J Green--------------------- Nov-12",
" 232 Richard Aust (NPR)---------------- Oct-12",
" 231 Kris Scott------------------------ Sep-12",
" 230 Andy Wade------------------------- Sep-12",
" 229 Simon Manson---------------------- Sep-12",
" 228 Bob Kelly (NPR)------------------- Jul-12",
" 227 Stephen Coveny-------------------- May-12",
" 226 Keith Chetwood-------------------- May-12",
" 225 Pamela Brooks--------------------- May-12",
" 224 Alan Lea (NPR)-------------------- May-12",
" 223 Jill Wright----------------------- May-12",
" 222 Trevor Prew----------------------- May-12",
" 221 Frank Baillie--------------------- Nov-11",
" 220 Andy Merrick---------------------- Nov-11",
" 219 Peter Young----------------------- Oct-11",
" 218 Ian Roberts (NPR)----------------- Oct-11",
" 217 Chris Braund---------------------- Oct-11",
" 216 Antonio Garofalo------------------ Sep-11",
" 215 Dave Evans (NPR)------------------ Jul-11",
" 214 Andy N Sutton--------------------- Jul-11",
" 213 Derek Snaith---------------------- Jul-11",
" 212 Liz Nicholas---------------------- Jul-11",
" 211 Andrew Gregory (NPR)-------------- Jun-11",
" 210 Bill Shaw------------------------- Jun-11",
" 209 Simon Bristow (NPR)--------------- Jun-11",
" 208 Malcolm Gilbertson---------------- Jun-11",
" 207 Crowdie (Clair's dog)(NPR)-------- May-11",
" 206 Clair Hutchings------------------- May-11",
" 205 Wendy Price (NPR)----------------- Apr-11",
" 204 Bob Price (NPR)------------------- Apr-11",
" 203 Kevin Ryder----------------------- Nov-10",
" 202 Carole Ryder---------------------- Nov-10",
" 201 John Paul Wilkinson--------------- Oct-10",
" 200 Stan Appleton--------------------- Oct-10",
" 199 Ian Davis------------------------- Aug-10",
" 198 Mark Lloyd------------------------ Aug-10",
" 197 David Rowlands (NPR)-------------- Jul-10",
" 196 David Findel-Hawkins ------------- Jun-10",
" 195 Merrian Lancaster (NPR)----------- Jun-10",
" 194 Malcolm Andrew-------------------- May-10",
" 193 Steven Turnbull------------------- May-10",
" 192 John Nudds (NPR)------------------ Mar-10",
" 191 Steve Allen (NPR)----------------- Mar-10",
" 190 Chris Clissold-------------------- Nov-09",
" 189 Phil Clayton---------------------- Oct-09",
" 188 Dave Corby------------------------ Oct-09",
" 187 Jean Bowers----------------------- Sep-09",
" 186 John Robert Colquhoun------------- Sep-09",
" 185 Martin Shallcross (NPR)----------- Sep-09",
" 184 Howard Sowerby-------------------- Sep-09",
" 183 Kevan Guest----------------------- Aug-09",
" 182 Mick Moore------------------------ Aug-09",
" 181 Anthony Rowe---------------------- Jul-09",
" 180 Robert Horridge------------------- Jun-09",
" 179 Michael Earnshaw------------------ May-09",
" 178 Anton Ciritis (NPR)--------------- Apr-09",
" 177 Carole Engel---------------------- Apr-09",
" 176 Janet Jackson--------------------- Mar-09",
" 175 Graham Jackson-------------------- Mar-09",
" 174 Wendy Dodds----------------------- Dec-08",
" 173 Ralph Henderson------------------- Dec-08",
" 172 Osian ab Ifan--------------------- Nov-08",
" 171 Liz Halpin------------------------ Nov-08",
" 170 Garth Fenton---------------------- Sep-08",
" 169 Elaine Fenton--------------------- Sep-08",
" 168 Ian Thomas------------------------ Jul-08",
" 167 Sue Dalton------------------------ Jul-08",
" 166 Andy West------------------------- Jul-08",
" 165 Des Taylor------------------------ Jul-08",
" 164 Barry Brown (NPR)----------------- Feb-08",
" 163 David M Bratt (NPR)--------------- Dec-07",
" 162 Christopher Litherland------------ Nov-07",
" 161 Jon Baldwin----------------------- Oct-07",
" 160 Barry Baldwin--------------------- Oct-07",
" 159 Peter Charlton (NPR)-------------- Oct-07",
" 158 Valerie Crookes (NPR)------------- Oct-07",
" 157 Bill Bowers----------------------- Oct-07",
" 156 Eric Hardman (NPR)---------------- Sep-07",
" 156 Eilir Evans (NPR)----------------- Aug-07",
" 155 Debbie Evans (NPR)---------------- Aug-07",
" 154 Steve Wilby (NPR)----------------- Aug-07",
" 153 Owen Brown (NPR)------------------ Aug-07",
" 152 Jonathan Curry-------------------- Jul-07",
" 151 Steve Lewis----------------------- Jul-07",
" 150 Peter Stubbs (NPR)---------------- Jun-07",
" 149 Linda Dworowski (NPR)------------- Jun-07",
" 148 Richard Edward Moss--------------- Apr-07", 
" 147 Shaun Woodward-------------------- May-07",
" 146 Ian Rear-------------------------- May-07",
" 146 Stephen Dixon--------------------- Mar-07",
" 145 John Marshall--------------------- Sep-06",
" 144 Paul Jensen----------------------- Sep-06",
" 143 Linda Jensen---------------------- Sep-06",
" 142 Brian Green (NPR)----------------- Sep-06",
" 141 Carole Green (NPR)---------------- Sep-06",
" 140 Simon Puddifoot------------------- Aug-06",
" 138 John Harvey----------------------- Aug-06",
" 138 Elizabeth Harvey------------------ Aug-06",
" 137 Ian Hildich----------------------- Jul-06",
" 136 Frank Stoddart (NPR)-------------- Jul-06",
" 135 Eric Povall----------------------- Jul-06",
" 134 Graham Phillips------------------- Jun-06",
" 133 Chris Deane----------------------- Jun-06",
" 132 Cyril Deeming--------------------- May-06",
" 131 John Price------------------------ Dec-05",
" 130 Mick Langton---------------------- Nov-05",
" 129 Michelle Sergeant----------------- Nov-05",
" 128 Eddie Broome (NPR)---------------- Aug-05",
" 127 David Irons----------------------- Jul-05",
" 126 Neil Stafford--------------------- May-05",
" 125 Peter Roberts (NPR)--------------- May-05",
" 124 Graham Illing--------------------- May-05",
" 123 Peter Fairhurst------------------- Feb-05",
" 122 Tim Gardner----------------------- Feb-05",
" 121 Martin Pearson-------------------- Nov-04",
" 120 Michael Wray---------------------- Oct-04",
" 119 Kathy Edwards--------------------- Oct-04",
" 118 John Edwards---------------------- Oct-04",
" 117 Jeff Parr------------------------- Sep-04",
" 116 Graeme Crow----------------------- Sep-04",
" 115 Barrie Trigg---------------------- Sep-04",
" 114 Jeff Bridge----------------------- Sep-04",
" 113 John Burn------------------------- Jun-04",
" 112 Christine Weller------------------ Jun-04",
" 111 Richard Litherland---------------- Apr-04",
" 110 Sonja Brentley-------------------- Dec-03",
" 109 Alan Brook------------------------ Nov-03",
" 108 Chris Harle----------------------- Oct-03",
" 107 David C Bratt--------------------- Sep-03",
" 106 Jess Milligan--------------------- Sep-03",
" 105 Malcolm Renshaw (NPR)------------- Sep-03",
" 104 Dave Beresford-------------------- Jun-03",
" 103 Clare Holdcroft------------------- Jun-03",
" 102 John Holmes----------------------- Jun-03",
" 101 Alan Burnet----------------------- Jun-03",
" 100 Cheryl Burnett-------------------- Jun-03",
"  99 Stephen Brown--------------------- May-03",
"  98 Ursula Stubbings------------------ Feb-03",
"  97 Caron Tan------------------------- Dec-02",
"  96 Jeremy Ward (NPR)----------------- Nov-02",
"  95 John Arkell----------------------- Nov-02",
"  94 Dave Cattell (NPR)---------------- Oct-02",
"  93 Charles Leventon------------------ Aug-02",
"  92 James Cain------------------------ Aug-02",
"  91 Brian Key------------------------- Jul-02",
"  90 Nicholas Key---------------------- Jul-02",
"  89 Bob Garrett----------------------- Jul-02",
"  88 David Richards-------------------- Jul-02",
"  87 Steve Taylor---------------------- Jun-02",
"  86 Peter Standing-------------------- Jun-02",
"  85 Raymond Myers--------------------- Jun-02",
"  84 Frank Yates----------------------- May-02",
"  83 Alison Fox------------------------ Apr-02",
"  82 Martin Thomerson (2 rnds NPR)----- Jan-02",
"  81 Graham Brookes-------------------- Dec-01",
"  80 Jerzy Matuszewski----------------- Aug-01",
"  79 Andy Sutton----------------------- Jul-01",
"  78 Andy Mohun-Smith------------------ Dec-00",
"  77 Rupert Booth---------------------- Dec-00",
"  76 Stephen Walker-------------------- Nov-00",
"  75 Richard Tait---------------------- Oct-00",
"  74 David Johnston-------------------- Oct-00",
"  73 Kathryn Willis-------------------- Oct-00",
"  72 Graham Willis--------------------- Oct-00",
"  71 Chris Crocker--------------------- Aug-00",
"  70 Paul Norman----------------------- Jul-00",
"  69 Andrew Copley--------------------- May-00",
"  68 Don Smithies---------------------- Mar-00",
"  67 Martin Richardson----------------- Dec-99",
"  66 Ian Rae--------------------------- Dec-99",
"  65 Jason Gregory--------------------- Dec-99",
"  64 Becky Hindle---------------------- Dec-99",
"  63 George Wilks---------------------- Dec-99",
"  62 Neville Cohen--------------------- Dec-99",
"  61 Jane Gill------------------------- Dec-99",
"  60 Paul Sollis----------------------- Oct-99",
"  59 Martyn Thurston------------------- Oct-99",
"  58 Michael Jacobs-------------------- Oct-99",
"  57 Peter Mallowan-------------------- Sep-99",
"  56 Frances Wilson-------------------- Aug-99",
"  55 Mark Jump------------------------- Aug-99",
"  54 Christina Jump-------------------- Aug-99",
"  53 George Ross----------------------- Aug-99",
"  52 Christine Roache------------------ Jul-99",
"  51 David Purchase (NPR)-------------- Jun-99",
"  50 Ian Watson------------------------ Apr-99",
"  49 Stuart Carter--------------------- Feb-99",
"  48 Martin Scott---------------------- Jan-99",
"  47 John Fenwick---------------------- Jan-99",
"  46 Andrew West----------------------- Dec-98",
"  45 Robert Mitchell------------------- Dec-98",
"  44 Danny Allen----------------------- Nov-98",
"  43 Chris Pearson--------------------- Sep-98",
"  42 Brian Graves---------------------- Aug-98",
"  41 Jean Pickford--------------------- Jul-98",
"  40 David Pickford-------------------- Jul-98",
"  39 D.H. Barham----------------------- Oct-97",
"  38 Chris Bullard--------------------- Sep-97",
"  37 Keith Abbott---------------------- Sep-97",
"  36 Frank Meacham--------------------- Aug-97",
"  35 Mike Baker (NPR)------------------ Jul-97",
"  34 Alan Castle----------------------- May-97",
"  33 Martin Hudson--------------------- Mar-97",
"  32 Dai Rowlands---------------------- Oct-96",
"  31 Margaret Waller------------------- Oct-96",
"  30 Vivien Crowder-------------------- Aug-96",
"  29 Geoff Crowder--------------------- Aug-96",
"  28 Nicolas Kingston------------------ Aug-96",
"  27 Deborah Seed---------------------- Jun-96",
"  26 Christopher Watson---------------- Jun-96",
"  25 Stephen Glasper------------------- Jun-96",
"  24 Gordon Adshead-------------------- Jun-96",
"  23 Mike Halpin (2 rounds)------------ May-96",
"  22 David Hoyle----------------------- Apr-96",
"  21 Rob Woodall----------------------- Apr-96",
"  20 Anthony Weetman------------------- Nov-95",
"  19 Peter Hughes---------------------- Oct-95",
"  18 Yong Tay-------------------------- Oct-95",
"  17 Robert Don------------------------ Oct-95",
"  16 Myrddyn Phillips------------------ Aug-95",
"  15 Rod Kearny------------------------ Apr-95",
"  14 Kevin Hostford-------------------- Dec-94",
"  13 Alan Poxon------------------------ Oct-94",
"  12 Philip Kearney-------------------- Aug-94",
"  11 Peter Wilson---------------------- Aug-94",
"  10 Iain Thow------------------------- Dec-93",
"   9 Cherry Kirby---------------------- Nov-93",
"   8 David Green----------------------- Aug-93",
"   7 Geoffrey Carter------------------- Aug-93",
"   6 Andy Moffat----------------------- Jul-93",
"   5 Valerie Moffat-------------------- Jul-93",
"   4 Aled Owen------------------------- May-93",
"   3 Mike Kirby------------------------ Aug-92",
"   2 John Nuttall (3 rounds 2NPR)------ Mar-90",
"   1 Anne Nuttall (3 rounds 2NPR)------ Mar-90"
);
