var completers = new Array(
" 175 Erwynj---------------------------- Dec-24",
" 174 Megan Dunster--------------------- Jun-24",
" 173 Jonathan England------------------ Apr-24",
" 172 Sioned Rees Davies---------------- Apr-24",
" 171 Scott Grove----------------------- Jan-24",
" 170 Graham Smith---------------------- Nov-23",
" 169 Thomas Smith---------------------- Nov-23",
" 168 Szymon Zareba--------------------- Oct-23",
" 167 David Fletcher-------------------- Aug-23",
" 166 Ed Casey-------------------------- Aug-23",
" 165 Sharon Casey---------------------- Aug-23",
" 164 Mick Peakman---------------------- Aug-23",
" 163 Joe Nuttall----------------------- Jun-23",
" 162 Tara Nuttall---------------------- Jun-23",
" 161 George Tod------------------------ May-23",
" 160 Ric Keeling----------------------- Sep-22",
" 159 Erwyn Jones----------------------- Sep-22",
" 158 Delia Roberts--------------------- May-21",
" 157 Iwan Williams--------------------- May-21",
" 156 Erwyn Jones----------------------- Apr-21",
" 155 Nathan Parry---------------------- Feb-20",
" 154 Robert Massey--------------------- Jan-20",
" 153 Peter Knight---------------------- Apr-19",
" 152 Eilir Jones----------------------- Sep-18",
" 151 Alex Hardisty--------------------- Sep-18",
" 150 Michael Murray-------------------- Sep-18",
" 149 Matthew Myerscough---------------- Sep-18",
" 148 Mark Trengove--------------------- May-18",
" 147 Graham Jelley--------------------- Oct-17",
" 146 Andy Moon------------------------- Apr-17",
" 145 Sarah Marlor---------------------- Apr-17",
" 144 Tom Garrod------------------------ Sep-16",
" 143 Akke Post------------------------- Jun-16",
" 142 Malcolm (Sunshine) Rogers--------- Sep-15",
" 141 Anne Rogers----------------------- Sep-15",
" 140 Ben Hardman (Aged 12)------------- Aug-15",
" 139 Eddie Hardman (Aged 11)----------- Aug-15",
" 138 Mark Lloyd------------------------ Aug-15",
" 137 Dianne Williams------------------- Jul-15",
" 136 Adrian Ives----------------------- Jun-15",
" 135 James Burnham--------------------- Apr-15",
" 134 Ian Cox -------------------------- Jan-15",
" 133 David Tomlinson------------------- Dec-14",
" 132 Dave Aston------------------------ Sep-14",
" 131 Ben Aston------------------------- Sep-14",
" 130 Sian Williams--------------------- Jun-14",
" 129 Rob Williams---------------------- Jun-14",
" 128 Adrian Doling--------------------- Nov-14",
" 127 Jason Till------------------------ Aug-14",
" 126 Keith Williams-------------------- Sep-14",
" 125 Gill Sanderson-------------------- Sep-14",
" 124 Steve Sanderson------------------- Sep-14",
" 123 Michael Cotton-------------------- Jul-14",
" 122 Huw Idris Jones------------------- Jun-14",
" 121 John Barnard---------------------- Jun-14",
" 120 Jenny Barnard--------------------- Jun-14",
" 119 Diane Salt------------------------ Jun-14",
" 118 Allan Salt------------------------ Jun-14",
" 117 Peter Richmond-------------------- Apr-14",
" 116 Alistair Pooler------------------- Mar-14",
" 115 Graham Coleman-------------------- Aug-13",
" 114 Gerald A. Davies------------------ Jul-13",
" 113 Sally Dodwell--------------------- Jul-13",
" 112 Tim Summers----------------------- May-13",
" 111 Simon Baker----------------------- Apr-13",
" 110 Tim Barnes------------------------ Dec-12",
" 109 Derek Roberts--------------------- Aug-12",
" 108 Roslyn Connolly------------------- Aug-12",
" 107 Peter Stuart---------------------- Aug-12",
" 106 Peter Young----------------------- May-12",
" 105 Flo (Rob and Becki's dog)--------- Dec-11",
" 104 Jessie (Rob and Becki's dog)------ Dec-11",
" 103 Rob Johnson----------------------- Dec-11",
" 102 Becki Johnson--------------------- Dec-11",
" 101 Mike Day-------------------------- Oct-11",
" 100 Howard Smith---------------------- Sep-11",
"  99 Peter Kirkwood-------------------- Sep-11",
"  98 Brian Dodd------------------------ Aug-11",
"  97 Nigel Jones----------------------- Aug-11",
"  96 Paul Wells------------------------ May-11",
"  95 Rob Davies------------------------ May-11",
"  94 Bill Lloyd------------------------ Sep-10",
"  93 Peter Jameson--------------------- Sep-10",
"  92 Jonathan Tod---------------------- Sep-10",
"  91 Nicola Tod------------------------ Sep-10",
"  90 Max Wiecko------------------------ Jul-10",
"  89 Brian Marsh----------------------- Jun-10",
"  88 Simon Griffiths------------------- Jun-10",
"  87 Tony Herraty---------------------- May-10",
"  86 Stuart Hyde----------------------- May-10",
"  85 Steve Allen----------------------- Nov-09",
"  84 Haydn Davies---------------------- Oct-09",
"  83 Jim Linton------------------------ Sep-09",
"  82 Andy Gourlay---------------------- Jul-09",
"  81 Paul Kimsey----------------------- Jul-09",
"  80 Jim MacDonald--------------------- Jul-09",
"  79 Rachel Marrington----------------- Jul-09",
"  78 Dafydd Davies (2 rounds)---------- Mar-09",
"  77 Aled Williams--------------------- Dec-08",
"  76 Malcolm Gilbertson---------------- Oct-08",
"  75 Steve Ward------------------------ Aug-08",
"  74 Robert Morley--------------------- Aug-08",
"  73 Steve Casey----------------------- Aug-08",
"  72 John Broom------------------------ Jul-08",
"  71 Andrew Archer--------------------- Jun-08",
"  70 Peter Hinxman--------------------- Apr-08",
"  69 Stewart Burley-------------------- Feb-08",
"  68 Andy Orchard---------------------- Sep-07",
"  67 Meirion Evans--------------------- Sep-07",
"  66 Nicky Viner----------------------- Aug-07",
"  65 Phil Viner------------------------ Aug-07",
"  64 Ian Marshall---------------------- Aug-07",
"  63 Richard Harris-------------------- Jun-07",
"  62 Russell Moseley------------------- May-07",
"  61 Jane Hawkins---------------------- May-07",
"  60 David Caddick--------------------- Apr-07",
"  59 Malcolm Bee----------------------- Jan-07",
"  58 Kevin Jones----------------------- Jan-07",
"  57 Carol Gruffydd-------------------- Jan-07",
"  56 Nigel Thomas---------------------- Dec-06",
"  55 Mair Lloyd Evans------------------ Oct-06",
"  54 Paul Cassidy---------------------- Sep-06",
"  53 Pat West-------------------------- Sep-06",
"  52 Richard West---------------------- Sep-06",
"  51 John Warren----------------------- Aug-06",
"  50 Bruce Strong---------------------- Jul-06",
"  49 Trevor Ansell--------------------- Oct-05",
"  48 Mark Creswell--------------------- Aug-05",
"  47 Bridget Inns---------------------- Aug-05",
"  46 Allister McNeill------------------ Jul-05",
"  45 Keri James------------------------ May-05",
"  44 Bill Lansbury--------------------- Mar-05",
"  43 Bill Lansbury's dog--------------- Mar-05",
"  42 Phil Humphreys-------------------- Sep-04",
"  41 Ian Bensted----------------------- Aug-04",
"  40 Ellie Bensted--------------------- Aug-04",
"  39 Bill Lancashire------------------- Aug-04",
"  38 George Tunstall------------------- Jun-04",
"  37 David Passey---------------------- May-04",
"  36 Paul Rudkin----------------------- Oct-03",
"  35 Mike Steggles--------------------- Oct-03",
"  34 Eric Williams--------------------- Oct-03",
"  33 John Burn (2 rounds)-------------- Sep-03",
"  32 David Nicholson------------------- Aug-03",
"  31 Roy Tunstall---------------------- Aug-03",
"  30 Eric Johnson---------------------- Aug-03",
"  29 Steve Wilby----------------------- Jul-03",
"  28 Scott Butterworth----------------- Apr-03",
"  27 Geoff Passey---------------------- Jan-03",
"  26 Dave Jarvis----------------------- Jan-03",
"  25 Phil Lloyd Jones------------------ Jan-03",
"  24 Myrddyn Phillips (16 rounds)------ Sep-02**",
"  23 David Stearne--------------------- Oct-02",
"  22 Tom Hardman (2 rounds)------------ Aug-02",
"  21 Derek Ivens----------------------- Aug-02",
"  20 David Bingham--------------------- Jun-02",
"  19 Colin Waines---------------------- Apr-02",
"  18 Susan Waines---------------------- Apr-02",
"  17 Mervyn Probert-------------------- Jun-01",
"  16 Colin Mansell--------------------- Oct-00",
"  15 Mrs Mansell----------------------- Oct-00",
"  14 Iain Chippendale------------------ Oct-00",
"  13 Eryl Selly (2 rounds)------------- Jun-00**",
"  12 Mark Picktall--------------------- Jun-00",
"  11 Mal Davies------------------------ Dec-99",
"  10 Tom Alves------------------------- Oct_98",
"  9 Sarah_Jane Alves------------------ Oct-98",
"  8 David Walker---------------------- Oct-98",
"  7 Ed Humphreys---------------------- Aug-98",
"  6 John Burton----------------------- Sep-96",
"  5 Dewi Jones (3 rounds)------------- Sep-96**",
"  4 Ann Bowker------------------------ Jun-96",
"  3 Tim Jones------------------------- Jun-96",
"  2 Rita Selly------------------------ Jul-95",
"  1 Alan Taylor----------------------- "
);
